### PR TITLE
👷 Add Node.js CI

### PR DESCRIPTION
**Pull request by lmachens**
This workflow builds and tests the project with different Node versions.

### CODE REVIEW

**Review by m-wiemers — APPROVED** [review]
Wow

**Review by JuKahl — APPROVED** [review]
GJ 💪

**Review by RonjaMeinecke — APPROVED** [review]
GJ💪

**Review by sweisz — APPROVED** [review]
LGTM :)

**Review by mewiemers — APPROVED** [review]
LGTM🚀

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by ShiningElektra — APPROVED** [review]
👍

**Review by mrana17 — APPROVED** [review]
gj 🚀

**Pull request merged**
