### PR TITLE
➕ Add storybook 

### PR DESCRIPTION
**Pull request by lmachens**
- [`npx sb init`](https://storybook.js.org/docs/react/get-started/install)
- Remove example stories folder
- Create components folder with example Button component
- Set stories folder in `.storybook/main.js`
- Load example component in `pages/index.tsx`
- Ignore `/storybook-static`
- Add `.eslintignore`

### CODE REVIEW

**Review by RonjaMeinecke — APPROVED** [review]
GJ 😃

**Review by fre-ben — APPROVED** [review]
LGTM 💯

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by mrana17 — APPROVED** [review]
lgtm 🚀

**Review by m-wiemers — APPROVED** [review]
Wow. Amazing ✨

**Pull request merged**
