### PR TITLE
➕ Add TypeScript

### PR DESCRIPTION
**Pull request by lmachens**
Followed instructions on [Next.js TypeScript Guide](https://nextjs.org/docs/basic-features/typescript)

In addition, I prettified auto generated tsconfig.json.

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by mrana17 — APPROVED** [review]
🚀 lgtm

**Review by JuKahl — APPROVED** [review]
lgtm 💪

**Review by m-wiemers — APPROVED** [review]
Wow. What a feast for the eyes

**Pull request merged**
